<a href="https://colab.research.google.com/github/Athul-042/Development-of-AI-Response-Validation-System-with-Hallucination-Detection-Assistance/blob/main/Sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:

import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")

conn.execute("""
CREATE TABLE Employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER,
    age INTEGER
)
""")

conn.executemany("""
INSERT INTO Employees VALUES (?, ?, ?, ?, ?)
""", [
    (1, "Arun", "IT", 60000, 23),
    (2, "Bala", "HR", 45000, 25),
    (3, "Charan", "IT", 75000, 24),
    (4, "Divya", "Sales", 50000, 22),
    (5, "Ezhil", "HR", 45000, 26),
    (6, "Farah", "IT", 80000, 27),
    (7, "Gokul", "Sales", 55000, 23)
])

conn.commit()

print("Database created successfully!")

Database created successfully!

In [11]:

pd.read_sql_query("SELECT * FROM Employees", conn)

   id    name department  salary  age
0   1    Arun         IT   60000   23
1   2    Bala         HR   45000   25
2   3  Charan         IT   75000   24
3   4   Divya      Sales   50000   22
4   5   Ezhil         HR   45000   26
5   6   Farah         IT   80000   27
6   7   Gokul      Sales   55000   23

In [12]:

pd.read_sql_query("""
SELECT name, salary
FROM Employees
WHERE salary > 50000
""", conn)

     name  salary
0    Arun   60000
1  Charan   75000
2   Farah   80000
3   Gokul   55000

In [13]:

pd.read_sql_query("""
SELECT name, salary
FROM Employees
ORDER BY salary DESC
""", conn)

     name  salary
0   Farah   80000
1  Charan   75000
2    Arun   60000
3   Gokul   55000
4   Divya   50000
5    Bala   45000
6   Ezhil   45000

In [14]:

pd.read_sql_query("""
SELECT MAX(salary) AS highest_salary
FROM Employees
""", conn)

   highest_salary
0           80000

In [15]:

pd.read_sql_query("""
SELECT department, COUNT(*) AS employee_count
FROM Employees
GROUP BY department
""", conn)

  department  employee_count
0         HR               2
1         IT               3
2      Sales               2

In [16]:

pd.read_sql_query("""
SELECT MAX(salary) AS second_highest_salary
FROM Employees
WHERE salary < (SELECT MAX(salary) FROM Employees)
""", conn)

   second_highest_salary
0                  75000

In [17]:

pd.read_sql_query("""
SELECT department, AVG(salary) AS average_salary
FROM Employees
GROUP BY department
""", conn)

  department  average_salary
0         HR    45000.000000
1         IT    71666.666667
2      Sales    52500.000000

In [18]:

pd.read_sql_query("""
SELECT salary, COUNT(*) AS frequency
FROM Employees
GROUP BY salary
HAVING COUNT(*) > 1
""", conn)

   salary  frequency
0   45000          2

In [19]:

pd.read_sql_query("""
SELECT department, AVG(salary) AS average_salary
FROM Employees
GROUP BY department
""", conn)

  department  average_salary
0         HR    45000.000000
1         IT    71666.666667
2      Sales    52500.000000

In [20]:

pd.read_sql_query("""
SELECT name, salary
FROM Employees
WHERE salary > (SELECT AVG(salary) FROM Employees)
""", conn)

     name  salary
0    Arun   60000
1  Charan   75000
2   Farah   80000

In [21]:

pd.read_sql_query("""
SELECT name, salary,
       DENSE_RANK() OVER (ORDER BY salary DESC) AS salary_rank
FROM Employees
""", conn)

     name  salary  salary_rank
0   Farah   80000            1
1  Charan   75000            2
2    Arun   60000            3
3   Gokul   55000            4
4   Divya   50000            5
5    Bala   45000            6
6   Ezhil   45000            6

In [22]:
pd.read_sql_query("""
SELECT *
FROM Employees
WHERE name LIKE 'A%'
""", conn)

   id  name department  salary  age
0   1  Arun         IT   60000   23

In [23]:
pd.read_sql_query("""
SELECT name, salary
FROM Employees
WHERE salary BETWEEN 50000 AND 75000
""", conn)

     name  salary
0    Arun   60000
1  Charan   75000
2   Divya   50000
3   Gokul   55000

In [24]:
pd.read_sql_query("""
SELECT department, SUM(salary) AS total_salary
FROM Employees
GROUP BY department
""", conn)

  department  total_salary
0         HR         90000
1         IT        215000
2      Sales        105000

In [25]:
pd.read_sql_query("""
SELECT name, age
FROM Employees
WHERE age > (SELECT AVG(age) FROM Employees)
""", conn)

    name  age
0   Bala   25
1  Ezhil   26
2  Farah   27